---
- name: Check if Git installed and install if it isn't
  hosts: all
  become: true

  tasks:
   - name: check if git installed
     ansible.builtin.command: git --version
     register: output
     ignore_errors: yes

   - name: Install if not installed
     ansible.builtin.apt:
       name: git
       state: present
     when:
       output.failed
 
